### ISSUE TITLE
ES Module syntax not yet supported in Node

### ISSUE THREAD

**Issue by defrex** [chrisbenincasa/berglas-node#1]
Hello, thanks for the useful package. It solves my need perfectly.

However, it currently doesn't work due to the ES Module import syntax, which isn't currently supported in node.js. I assume you're using Babel or similar, but most build toolchains (or at least, mine) don't compile `node_modules`.

```
/home/defrex/code/abacus/api/node_modules/berglas-node/index.js:1
(function (exports, require, module, __filename, __dirname) { import { Storage } from "@google-cloud/storage";
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by chrisbenincasa** [comment]
Thanks for the issue, I'm glad this is solving your need! You're totally right - I overlooked this while porting this out of our project. 

This should be fixed in 266095ca9f0cb43110cda54c811f7b4597b7df8d and [version 1.0.1](https://www.npmjs.com/package/berglas-node/v/1.0.1) now. Let me know if you have any issues!

**Comment by defrex** [comment]
Thanks for the quick fix! :pray: 

However, it seems you missed a spot.

```
/home/defrex/code/abacus/api/node_modules/berglas-node/index.js:88
export { resolve, substitute };
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by chrisbenincasa** [comment]
Agh! Just merged #2 - was moving a bit too quickly.

**Comment by chrisbenincasa** [comment]
v1.0.2 should be available on NPM now!

**Comment by defrex** [comment]
Thanks!
